{% set name = "eo-learn-io" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 95e0e5e0d540e64de77c9bdae140de4b5503a6561ac644e8dc7216394038adea

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - eo-learn-core
    - python >=3.5
    - rasterio

test:
  imports:
    - eolearn
    - eolearn.io

about:
  home: https://github.com/sentinel-hub/eo-learn
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A collection of input/output utilities and EOTasks
  doc_url: https://eo-learn.readthedocs.io/en/latest/eolearn.io.html
  dev_url: https://github.com/sentinel-hub/eo-learn

extra:
  recipe-maintainers:
    - mxr-conda
    - mwilson8
    - dcunn
    - oblute
    - rluria14
    - benhuff
